# Generated by Django 4.2.4 on 2023-10-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('description', models.TextField()),
                ('time', models.TimeField()),
                ('type', models.CharField(max_length=200)),
            ],
        ),
    ]
