# Generated by Django 4.2.4 on 2023-12-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_headeraricle_madrassa_plumesoufis_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outaz_biblio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
            ],
        ),
    ]
