# Generated by Django 4.2.4 on 2023-12-02 02:41

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dahira', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=200)),
                ('Prenom', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Téléphone', models.CharField(max_length=12)),
                ('Pays', django_countries.fields.CountryField(max_length=2)),
                ('Adresse', models.CharField(max_length=200)),
            ],
        ),
    ]
