# Generated by Django 4.2.4 on 2023-12-02 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dahira', '0002_formulaires'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulaires',
            old_name='Adresse',
            new_name='adresse',
        ),
        migrations.RenameField(
            model_name='formulaires',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='formulaires',
            old_name='Nom',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='formulaires',
            old_name='Pays',
            new_name='pays',
        ),
        migrations.RenameField(
            model_name='formulaires',
            old_name='Prenom',
            new_name='prenom',
        ),
        migrations.RenameField(
            model_name='formulaires',
            old_name='Téléphone',
            new_name='tel',
        ),
    ]
