# Generated by Django 4.2.4 on 2023-12-05 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dahira', '0004_rename_formulaires_modelform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelForm',
            new_name='DevenirMembreForm',
        ),
    ]
