# Generated by Django 4.2.4 on 2023-12-16 02:53

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('dahira', '0005_rename_modelform_devenirmembreform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devenirmembreform',
            name='tel',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
