# Generated by Django 4.2.4 on 2023-12-16 02:58

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('dahira', '0006_alter_devenirmembreform_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devenirmembreform',
            name='tel',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
