# Generated by Django 4.2.4 on 2023-12-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dahira', '0009_alter_devenirmembreform_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devenirmembreform',
            name='tel',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
