# Generated by Django 4.2.4 on 2023-12-22 18:20

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dahira', '0010_alter_devenirmembreform_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devenirmembreform',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
