# Generated by Django 4.2.4 on 2023-10-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignement', '0005_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderEtoileDeLaFayda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(default='first_page1.jpg', upload_to='')),
            ],
        ),
    ]
